### PR TITLE
moved constants file to poplar and updated import statements

### PR DESCRIPTION
**Pull request by clementzach**
When installing forest using pip from the develop branch and running it, I get the following error:

ModuleNotFoundError: No module named 'forest.constants'

It looks like it stems from [this pull request](https://github.com/onnela-lab/forest/pull/73#issue-1120823998)

I solved the problem by moving the constants file to the poplar tree and updating the import statements

### CODE REVIEW

**Comment by clementzach** [comment]
I'm leaving this pull request here for someone else to see, and I'll merge it tonight if nobody says anything. It's possible that there's a better way to manage this problem.

**Review by hackdna — COMMENTED** [review]
Thanks for the PR. I have no issues installing Forest and running Bonzai, Jasmin, or Willow. Could you describe what and how were you running exactly, and what was the output?

**Comment by clementzach** [comment]
Hm. I must be doing something wrong. Here's code I use to reproduce the error. 

The error has happened on both my machine and on Debbie's machine

conda create --name clean_3_8 python=3.8
conda activate clean_3_8
pip install git+https://github.com/onnela-lab/forest@develop
python 
from forest.jasmine.traj2stats import gps_stats_main


Here's the traceback:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/SanDisk/opt/anaconda3/envs/clean_3_8/lib/python3.8/site-packages/forest/jasmine/traj2stats.py", line 21, in <module>
    from forest.bonsai.simulate_gps_data import bounding_box
  File "/Volumes/SanDisk/opt/anaconda3/envs/clean_3_8/lib/python3.8/site-packages/forest/bonsai/simulate_gps_data.py", line 21, in <module>
    from forest.constants import (ORS_API_BASE_URL, ORS_API_CALLS_PER_MINUTE,
ModuleNotFoundError: No module named 'forest.constants'

**Comment by hackdna** [comment]
Thanks for the detailed info! The issue is that the Forest package is not installing correctly for some reason and some files end up missing. I will look into why this is happening. As a workaround, you can run the code if you change you current directory to your local Forest git repo:
```
git clone git@github.com:onnela-lab/forest.git
cd forest
```

**Comment by hackdna** [comment]
I've applied a fix to the develop branch. Please try again and let me know if it solved the issue.

**Comment by clementzach** [comment]
Works for me. Thanks so much!

**Pull request closed without merging**
