### PR TITLE
Provide default values to all text and call variables

### LINKED ISSUE #68: comm_logs_summaries() throws UnboundLocalError if texts data is empty while calls data is not empty
I was using forest on "Public Sample Beiwe Dataset" from Zenodo ([source](https://zenodo.org/record/1188879#.Yex2eljMJTY)) and I ran into an error when running `log_stats_main()`. I see it tracks to `comm_logs_summaries()` which throws an error b/c a local variable does not get defined if texts data is empty while calls data is not empty. There are 0 texts and 1 call in this data. 

I use Python 3.8.12.
I observed the same output as shown below when running on:
(a) Python environment that has forest `main` branch installed,
(b) Python environment that has forest `develop` branch installed. 

Reproducible example: 

```python
import pandas as pd
from forest.willow.log_stats import comm_logs_summaries
from platform import python_version

print(python_version())

ID = "6b38vskd"
text_data = pd.DataFrame.from_dict({})
call_data = pd.DataFrame.from_dict(
    {'timestamp': {0: 1454428647649},
     'UTC time': {0: '2016-02-02T15:57:27.649'},
     'hashed phone number': {0: 'ZlGtb-SRRIgOcHLBD02d2_F049naF0YZbCx_CeP7jss='},
     'call type': {0: 'Missed Call'},
     'duration in seconds': {0: 0}}
)
stamp_start = 1453837206
stamp_end = 1454634000
tz_str = "America/New_York"
option = "daily" 

stats_pdframe = comm_logs_summaries(ID, text_data, call_data, stamp_start, stamp_end, tz_str,option)
```
```
3.8.12
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/var/folders/sk/c14blb7s493_7lgzdq0m3sjm0000gn/T/ipykernel_51047/4226467727.py in <module>
     19 option = "daily"
     20 
---> 21 stats_pdframe = comm_logs_summaries(ID, text_data, call_data, stamp_start, stamp_end, tz_str,option)

~/opt/anaconda3/envs/forest_run/lib/python3.8/site-packages/forest/willow/log_stats.py in comm_logs_summaries(ID, df_text, df_call, stamp_start, stamp_end, tz_str, option)
     91         if option == 'daily':
     92             newline = [year, month, day, num_in_call, num_out_call, num_mis_call, num_uniq_in_call, num_uniq_out_call,
---> 93                   num_uniq_mis_call, total_time_in_call, total_time_out_call, num_s, num_r, num_mms_s, num_mms_r, num_s_tel,
     94                   num_r_tel, total_char_s, total_char_r,text_reciprocity_incoming,text_reciprocity_outgoing]
     95         if option == 'hourly':

UnboundLocalError: local variable 'num_s' referenced before assignment
```
Also, for future, what is the best way to show programmatically which forest commit/download date I am using? 

FYI @patricknnamdi (who also graciously shared code with group/me to learn how to use forest)

### PR DESCRIPTION
**Pull request by hackdna**
Fix #68

### CODE REVIEW

**Comment by martakarass** [comment]
I do not seem to be able to get `hackdna/default-values` working (same for current `develop`, see below). 

I used conda to create new environment to test this PR: 

```
conda create --name forest_test_default_values python=3.8
conda activate forest_test_default_values
conda install git pip
pip install mano
pip install git+https://github.com/onnela-lab/forest.git@hackdna/default-values
python
```
and then in python I have: 
```python
import mano
import sys  
import os
import mano.sync as msync
import time
import pandas as pd
import tempfile
from datetime import date
from forest.jasmine.traj2stats import gps_stats_main
```
the forest's import from the last line returns me an error now: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/martakaras/opt/anaconda3/envs/forest_test_default_values/lib/python3.8/site-packages/forest/jasmine/traj2stats.py", line 21, in <module>
    from forest.bonsai.simulate_gps_data import bounding_box
  File "/Users/martakaras/opt/anaconda3/envs/forest_test_default_values/lib/python3.8/site-packages/forest/bonsai/simulate_gps_data.py", line 21, in <module>
    from forest.constants import (ORS_API_BASE_URL, ORS_API_CALLS_PER_MINUTE,
ModuleNotFoundError: No module named 'forest.constants'
```
I checked and **I do not** get such an error when I use `main` (`pip install git+https://github.com/onnela-lab/forest.git@main`) but **I do** get it when I use `develop` (`pip install git+https://github.com/onnela-lab/forest.git@develop`)

I wonder what is your advice to proceed? THave I missed something in the way I am trying to test it?  hanks a lot.

**Comment by hackdna** [comment]
Thanks for the detailed info! The issue is that the Forest package is not installing correctly for some reason and some files end up missing. I will look into why this is happening. As a workaround, you can run the code if you change you current directory to your local Forest git repo:
```
git clone git@github.com:onnela-lab/forest.git
cd forest
```

**Comment by hackdna** [comment]
I've added a fix to this branch. Please try again and let me know if it solved the issue.

**Comment by martakarass** [comment]
@[hackdna](https://github.com/hackdna) thanks, it worked! I added a PR to your branch, I think this PR will be good to go then

**Comment by hackdna** [comment]
I've pushed an update, please have a look when you get a chance.

**Review by martakarass — APPROVED** [review]

**Comment by martakarass** [comment]
Hi @hackdna whose role is to merge this pull request now: you (author) or me (reviewer)? I am trying to keep in mind the workflow you presented at the Forest meeting 2 weeks ago! :) Thanks.

**Comment by hackdna** [comment]
Thanks! We haven't discussed yet if the author or the reviewer should merge PRs. I will merge this one myself but we should probably let reviewers do that.

**Pull request merged**
