### PR TITLE
Fix bug in OpenStreetMaps locator code that showed if place of interest not in nearby locations of a pause

### PR DESCRIPTION
**Pull request by martakarass**
Fix bug in OpenStreetMaps locator code: add to check if place of interest (`place`) not in nearby locations of the current pause, skip to the next place of interest (previously, KeyError would appear if place of interest (`place`) not in nearby locations of the current pause)

### CODE REVIEW

**Comment by martakarass** [comment]
Note my branch is not passing checks on ubuntu due to "Run static type checking" of something which I believe my changes are not touching.

**Comment by hackdna** [comment]
FYI, the build is failing due to an issue in Bonsai: #123

**Comment by martakarass** [comment]
> FYI, the build is failing due to an issue in Bonsai: #123

Thanks, @hackdna ! For my information, what is the procedure in such cases? Is it allowed that such a PR -- for which the build fails due to reasons independent of the PR's change -- is merged?

**Comment by hackdna** [comment]
Ideally, we fix the build first then merge.

**Comment by hackdna** [comment]
I've updated this branch with the latest code from develop. The build is fixed now.

**Review by GeorgeEfstathiadis — APPROVED** [review]

**Pull request merged**
