### PR TITLE
Get distance from ORS API when available

### PR DESCRIPTION
**Pull request by GeorgeEfstathiadis**
Change in `get_path` function:
> Get distance between two sets of coordinates from OpenRouteService returns instead of great_circle_dist function.

### CODE REVIEW

**Comment by clementzach** [comment]
Looks great!

Is there a reason why your new test doesn't use round()?

**Comment by GeorgeEfstathiadis** [comment]
> Looks great!
> 
> Is there a reason why your new test doesn't use round()?

Not really, there just is no need, since the distance returned is already rounded by the API

**Comment by clementzach** [comment]
> > Looks great!
> > Is there a reason why your new test doesn't use round()?
> 
> Not really, there just is no need, since the distance returned is already rounded by the API

Sounds great!

**Comment by clementzach** [comment]
@GeorgeEfstathiadis if you re-request a review from me I'll approve this.

**Review by clementzach — APPROVED** [review]
Looks great!

**Pull request merged**
