### PR TITLE
Avoid unnecessary casting of ints to floats in Willow output

### PR DESCRIPTION
**Pull request by hackdna**
This should resolve this error: https://github.com/onnela-lab/beiwe-discussions/issues/21#issuecomment-965554967

Note that `total_mins_in_call` and `total_mins_out_call` are still floats. I've fixed that in the attribute mappings Google sheet.

### CODE REVIEW

**Comment by biblicabeebli** [comment]
Ah crap, I responded to the wrong comment over on the blockers thread.

I resolved this issue on my eli/jasmine-quality-threshold branch that I've been working off of for the forest task updates due to renames.  Sorry about that, now we have a single issue half-covered on 3 threads.  My fault entirely.

This was my commit, I solved it by specifying the data type to a pandas dataframe indicating ints.
418a24d7428247f5c27a5d360c4a80d7016cc35a
(only seeing whitespace changes on that link, I did not intend to do that, I need to change my IDE settings for Forest so it doesn't do that.  lines 106 and 111 are the relevant changes.

Which solution is better in your opinion, also are there side effects I may not know about.

**Comment by hackdna** [comment]
No worries. The issue with wholesale casting is that not all columns are ints. Also, with this solution we remove some unnecessary code. Btw, I'm fine with removing trailing white space - it's part of cleanup that we need to do at some point.

**Comment by biblicabeebli** [comment]
I haven't tested this live on a server, but we are behind and I just don't have time to do an extra round of live testing.  It is time to get my branch merged into main right now with minimal extra changes.  This needs to be tested on a merged branch with my fix, my fix is objectively dumber than this one. my commit is 418a24d7428247f5c27a5d360c4a80d7016cc35a.

**Comment by hackdna** [comment]
The fix in 418a24d will result in data loss because it will convert all output values to ints - even the ones that need to remain as floats.

**Review by biblicabeebli — APPROVED** [review]
looks fine to me, you are much more informed about pandas datafram behavior.

**Comment by biblicabeebli** [comment]
Sorry this took a while.
I've updated the backend on a new branch called `willow-floatfields` and run a test on the staging server with it.

I'm going to click the close with comment button, and then update the backend branch to point at the new commit identifier that will be generated for `main`.

@hackdna please let me know your plans for version number updates of the pip package.  I have to manually uninstall and reinstall forest due to the exact behavior of a git commit target in a requirments file.  I don't like pushing such a git target to requirements files on the main `beiwe-backend` branch because that will deployments that I don't directly manage.  (hooray... that partcular and obscure pip behavior...)

**Comment by biblicabeebli** [comment]
wait what.... oh lol misread button it said close with comment.... I've done this about 20 times in my life, okay, trying to merge it manually... okay we are good and I don't need to update a git commit, hash is e72ac1d4fd36698a050867218fd5894c5ea16e9d.

**Comment by hackdna** [comment]
Thanks. It would be great to squash with merge next time to keep the main branch history clean and consistent.

I have not thought about version numbering because there was no plan to publish Forest in PyPI yet. Why not simply use hotfix and release branches in beiwe-backend? We should probably create an issue in beiwe-discussion to figure out a deployment strategy.

**Comment by biblicabeebli** [comment]
Sorry about the git history, in this case it was a fast-forward merge of iirc 3 commits, so I figured it was fine. I will try and do squashes on this repo in the future,

**Pull request closed without merging**
