### PR TITLE
adding new documentation md file: Accessing and decrypting Beiwe data

### PR DESCRIPTION
**Pull request by martakarass**
I created a new documentation MD file titled "Accessing and decrypting Beiwe data stored on Amazon S3". 

I believe it should fall under "MISC" category on the documentation website https://forest.beiwe.org/en/latest/; it is unclear to me if I should have explicitly specified something within this MD file in order to make it fall under "MISC" -- @hackdna please advise. Thank you!

I'd appreciate a content review from @biblicabeebli . Primarily, I hope to have checked if I am correctly using the wording of what we are doing (e.g., "reading in").

### CODE REVIEW

**Comment by biblicabeebli** [comment]
This is great.

I am seeing that there is a file path that includes your computer username, we should replace /Users/martakaras/Documents/... with ~/Documents/...

We should add this example IAM policy to the directions - in principle this should be a full set of directions for non-Onnela Lab Beiwe instances, but we can expect a reasonable level of general system administration competence.  Providing the policy should be enough.

In the AWS Online Console go to the IAM service and create a new policy that you can assign to an AWS user to grant them access to the S3 bucket and objects.  The example below contains both participant-specific and study-specific example lines, clean up and delete trailing commas as appropriate.  (Note that AWS has a 6,144 character limit on policy JSON length, if you are doing participant-based restriction you may need to split this up across several policies.)

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:GetObject",
            "Resource": [
                "arn:aws:s3:::NAME_OF_YOUR_BEIWE_S3_BUCKET",
                "arn:aws:s3:::NAME_OF_YOUR_BEIWE_S3_BUCKET/STUDY_ID*",
                "arn:aws:s3:::NAME_OF_YOUR_BEIWE_S3_BUCKET/CHUNKED_DATA/STUDY_ID*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::NAME_OF_YOUR_BEIWE_S3_BUCKET",
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "STUDY_ID*",
                        "CHUNKED_DATA/STUDY_ID*"
                    ]
                }
            }
        }
    ]
}
```


And we should add links to the documentation for the boto3 library, we make use of GetObject and ListObjectsV2, can you find a good spot to insert these?
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects_v2
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.get_object


After that just ping me and I'll approve the pull request.

**Comment by martakarass** [comment]
Thanks, @biblicabeebli ! 

I updated per your suggestions. I wasn't 100% clear if you were suggesting to add "Granting access to Amazon S3 bucket" section to this doc page, but I did.

**Comment by hackdna** [comment]
@martakarass you can add `aws_s3.md` to the Misc section of `index.md`: https://github.com/onnela-lab/forest/blob/develop/docs/source/index.md?plain=1#L23

**Comment by martakarass** [comment]
@hackdna I added add aws_s3.md to the Misc section of index.md, thanks!

**Comment by biblicabeebli** [comment]
looks good to me....

**Review by biblicabeebli — APPROVED** [review]
yup looks good

**Pull request merged**
