### PR TITLE
validate that something is a directory before counting it as an ID

### PR DESCRIPTION
**Pull request by clementzach**
A sycamore user encountered an error because they had another document in the folder with the user directories. I figured that something like that may happen again, so I added a check that IDs are folders.

### CODE REVIEW

**Comment by hackdna** [comment]
Thanks! Also, it'd be great to update the function docstring to mention that the `study_folder` is an absolute file path. Finally, I've seen this functionality replicated across the codebase, so I think it would be useful to move `get_ids()` to somewhere like `forest/forest/utils.py` (next to `constants.py`), so that it can be reused easily by all the trees.

**Comment by clementzach** [comment]
@hackdna Would it make sense to put this in `poplar.functions.helpers` instead? It seems like there are already some common functions there, and I wouldn't want to have everything in different places.

**Comment by clementzach** [comment]
@hackdna those extra checks are added.

Also, do you have any idea what stopped the test from passing [here](https://github.com/onnela-lab/forest/runs/6470938414?check_suite_focus=true)? It passed the next time even though I didn't change anything related to the bonsai tree. The two numbers are 0.001 off from each other, but they're already rounded. 

And, I was going to update `forest.willow.log_stats` to use the get_ids function, but that would involve a bunch of code changes to bring it to mypy and PEP8 compliance. Would you want me to do it in this PR or in a new one?

**Review by hackdna — CHANGES_REQUESTED** [review]
The `get_ids()` function would be used by more than one tree, so it does not make sense to place this kind of functions in a particular tree. Also, converting all Forest code to use this function in this PR would be out of scope (as you've noticed in the context of `forest.willow.log_stats`). This can happen whenever corresponding code is updated in the future.

I am not sure why `test_gen_basic_pause_location()` test started to fail. Were there were any changes in the code that it is testing? If not, this test may be too brittle and may be need to be improved. This may be a question for @GeorgeEfstathiadis since he is the author of that code.

**Comment by clementzach** [comment]
> The `get_ids()` function would be used by more than one tree, so it does not make sense to place this kind of functions in a particular tree. Also, converting all Forest code to use this function in this PR would be out of scope (as you've noticed in the context of `forest.willow.log_stats`). This can happen whenever corresponding code is updated in the future.

Hmm. I may have been confused about the poplar tree. 

The description of Poplar in the wiki is:

> Various common functions for data preparation, mainly used by other trees (e.g. time zone conversion, reading/writing)

I know that there are a few functions (such as forest.poplar.legacy.common_funcs.read_data) that are in use by both Jasmine and Willow. 

What kinds of functions should be put inside Poplar, and what kind of functions should be put in a forest/utils.py file? Or, should we just put all new common functions inside forest/utils.py and maybe move common functions from poplar to forest/utils.py sometime in the future?

**Comment by clementzach** [comment]
Okay! I'll move `get_ids` to forest.utils.py

Should I maintain the PEP8, mypy, and testing changes I did for `poplar.functions.helpers` or should I revert those changes?

**Comment by hackdna** [comment]
Sure, you can keep those changes, just need to update `flake8` to so that the updates files are no longer excluded from automated checks.

Also, it's worth checking which functions are actually in use. For example, it looks like `join_lists()` is not actually used anywhere, so it makes more sense to remove it instead of writing tests for it.

**Comment by clementzach** [comment]
Ok! Sorry for making this PR into a long one...

I double checked, and none of the functions in poplar.functions.helpers are actually used elsewhere in the package. A search for "org:onnela-lab functions.helpers" only returns results related to documentation and testing imports. In fact, the only part of poplar which was used by another module was poplar.legacy.common_funcs (which as the read_data function)

Maybe the correct thing to do would be to eventually move poplar.legacy.common_funcs to forest.utils.py, and then update the poplar documentation to say that it just has helpful functions for working with Beiwe data? We should discuss this in our meeting on Friday. 

Anyway, it seems like it wouldn't make sense to remove unused functions in `forest.poplar.functions.helpers` when poplar has so many unused functions.

**Review by hackdna — APPROVED** [review]

**Pull request merged**
