### PR TITLE
add checks for coordinates out of range

### PR DESCRIPTION
**Pull request by GeorgeEfstathiadis**
Adding a check to make sure coordinates are within range to avoid issues in the imputing process.

### CODE REVIEW

**Comment by clementzach** [comment]
This looks like a great guardrail! Good idea

**Review by clementzach — APPROVED** [review]
Look great!

**Comment by clementzach** [comment]
Sorry to revive this, but I just had the realization that for studies where data is anonymized (i.e. random numbers are added to latitude and longitude) it's possible that this error could be thrown for non-imputed (but fuzzed) latitude/longitude points. I believe that this shouldn't cause errors very frequently unless someone's location is near the North or South pole, but it's possible that it could cause a problem. 

It seems that for iOS at least, gps longitude will always be between -180 and 180, but latitude could conceivably be greater than or less than 90 (https://github.com/onnela-lab/beiwe-ios/blob/0dc02ca8db4693a1ec24c68e360a6c910a373a62/Beiwe/Managers/GPSManager.swift#L76C18-L76C18)

**Comment by GeorgeEfstathiadis** [comment]
@clementzach do you have any ideas on how to deal with this? Maybe we check latitude is between -95 and 95 or do you think it could be even more radical than that?

**Comment by hackdna** [comment]
IMHO, latitude should always be between -90 and 90, so the fuzzing needs to be fixed.

**Comment by clementzach** [comment]
I did more looking into this, and the Android offset is limited to a maximum of 1 degree (https://github.com/onnela-lab/beiwe-android/blob/3b000472cd0db108004b0b2045128feef34363d3/app/src/main/java/org/beiwe/app/storage/PersistentData.java#L549) and the iOS offset) as well as the iOS offset (https://github.com/onnela-lab/beiwe-ios/blob/0dc02ca8db4693a1ec24c68e360a6c910a373a62/Beiwe/Controllers/RegisterViewController.swift#L299C46-L299C46). I think that it's pretty unlikely that any of our study participants will be traveling within 1 degree of the north or South Pole, so I actually think we're probably fine with this check. 

My apologies, I should have looked more into the maximum amount of the offset before bringing you two into it

**Comment by clementzach** [comment]
For future reference, here’s code for the Android longitude offset. https://github.com/onnela-lab/beiwe-android/blob/3c13c755ce9d37123a680604fd9c3a235739b438/app/src/main/java/org/beiwe/app/listeners/GPSListener.kt#L159

**Comment by biblicabeebli** [comment]
@clementzach is it a bug that it is off by 1 degree? I feel like
```
val latitude = location.latitude + PersistentData.getLatitudeOffset()
val longitude = (location.longitude + PersistentData.getLongitudeOffset() + 180.0) % 360 - 180.0
```
should be
```
val latitude = location.latitude * PersistentData.getLatitudeOffset()
val longitude = ((location.longitude * PersistentData.getLongitudeOffset()) + 180.0) % 360 - 180.0
```

**Pull request merged**
